### ISSUE TITLE
大佬，想问下，怎么才会出现视频中的游戏结尾内容？

### ISSUE THREAD

**Issue by darbra** [linyiLYi/street-fighter-ai#20]
大佬，程序跑起来了。
请问怎么操作才能看到视频中的游戏通关的结尾部分，非常感谢。

**Comment by doninox** [comment]
我这也是 不停的就是一场对局

**Comment by Mistletoe0628** [comment]
> 我这也是 不停的就是一场对局

test.py 21行，是否重置改为False

**Comment by darbra** [comment]
> 

可以了大佬牛逼

**Comment by darbra** [comment]
> > 我这也是 不停的就是一场对局
> 
> test.py 21行，是否重置改为False

可以了 大佬牛逼
