### ISSUE TITLE
ROM Removal

### ISSUE THREAD

**Issue by JazzGlobal** [linyiLYi/street-fighter-ai#29]
Good work, but I'm worried you linking to the ROM will have negative ramifications for you. Be careful!

**Comment by JazzGlobal** [comment]
My motivations are not negative. I think this project is cool and am a developer as well! The only thing that worries me is the fact that the README says to get the ROM legally but then immediately links to a download for the ROM! Companies can be very serious about this stuff. I was just saying to be careful.

**Comment by 19245222** [comment]
> My motivations are not negative. I think this project is cool and am a developer as well! The only thing that worries me is the fact that the README says to get the ROM legally but then immediately links to a download for the ROM! Companies can be very serious about this stuff. I was just saying to be careful.

Aww, he thinks you are a dirty ass mutherfxxker. But in fact you're not. haha
