### ISSUE TITLE
运行画面静止不动

### ISSUE THREAD

**Issue by ack528** [linyiLYi/street-fighter-ai#34]
![mmexport1681911202507.png](https://user-images.githubusercontent.com/82737603/233091623-136355ff-780d-46af-80c1-3dc3f700c93e.png)

**Comment by ack528** [comment]
12400+3060ti

**Comment by chrsas** [comment]
参考 https://github.com/linyiLYi/street-fighter-ai/issues/6

**Comment by interiv** [comment]
不要替换那个dll文件,如果是已经替换造成了 画面静止一小会儿,就退出的话,重新安装 gym-retro就行了.我遇到的这个问题.分享个你.
