### ISSUE TITLE
Input two-player actions

### ISSUE THREAD

**Issue by quantumiracle** [linyiLYi/street-fighter-ai#46]
Hi, 

Thanks for open-sourcing this great project!

I'm wondering if it's possible to support controlling both side of players in the game, the env.step() will take two actions per step, one for each player. Any suggestion on how to support that?

**Comment by tonyxu99** [comment]
Yes. I have created a project based on Linyi's project. (https://github.com/tonyxu99/String_fighter_AI). I have saved a 2 player state. You can play against the AI. Later, I will figure out how to make two AIs fight and train each other.

**Comment by quantumiracle** [comment]
Thanks! Good job!

I tried it and it works. Just the frame rate seems to be a bit high and the human user may be hard to react.

**Comment by tonyxu99** [comment]
Thank you for trying my code. The speed is normal for me. Did you clone my whole project and use my version of "street_figher_customer_wrapper.py"? If you want to make the game slower, you can set the "tps" lower than 60 at the line#227 of interative.py.

**Comment by quantumiracle** [comment]
Thanks!
