### ISSUE TITLE
运行test.py以后跳出模拟器窗口画面是静止的，控制台没有报错

### ISSUE THREAD

**Issue by leapp** [linyiLYi/street-fighter-ai#6]
运行test.py以后跳出模拟器窗口，显示对战画面但是静止的不会动，控制台没有报错，请问是什么原因啊

**Comment by linyiLYi** [comment]
重新运行一次还会这样吗？有时我拖动窗口的时候画面会卡住

**Comment by leapp** [comment]
<img width="630" alt="微信图片_20230416163932" src="https://user-images.githubusercontent.com/6461191/232287111-cae2cdab-4173-4c16-bb07-006df558328f.png">

重新运行也是一样，控制台显示：Fighting Begins! 然后模拟器画面和控制台就卡住了

**Comment by hanniballam** [comment]
同问

**Comment by blueleafxp** [comment]
原因是因为下载的文件是zip 文件，不可以直接使用改名成rom.md,需要解压缩出来，把解压后的文件改名到rom.md,然后覆盖到教程中所述的目录，我通过gpt4 shooting了半天，结果是这个弱智问题
