### ISSUE TITLE
在Mac上的新问题

### ISSUE THREAD

**Issue by dead-lee** [linyiLYi/street-fighter-ai#76]
在mac上用pip安装gym-retro，无法装0.8版本的，只能安装0.7.1的，但是0.7也会安装失败。

**Comment by zhuopu88** [comment]
我也遇到这个问题，在win10上成功了，mac上不行，也是不能安装0.8

**Comment by dead-lee** [comment]
我folk了林哥的代码，在copilot的协助下，问题已经解决。现在可以在我的m2 MacBook pro上，基于最新的python运行。
https://github.com/dead-lee/street-fighter-ai
1. 依赖包全部更新。主要是gymnasium替换了gym，stable-retro替换了gym-retro.
2. stable-baselines3的最新版本，需要shimmy来处理gymnasium和gym的转换。
3. stable-retro需要clone下，来从源码编译安装。它自己的步骤写的可以，我在“echo 'export PATH="/opt/homebrew/opt/qt@5/bin:$PATH"' >> ~/.zshrc“这步遇到权限问题，copilot建议我用"sudo nano ~/.zshrc"来添加，解决了问题。
其他零零碎碎的问题都可以用copilot解决。
上个截图纪念下。
<img width="758" alt="image" src="https://github.com/user-attachments/assets/ac0176ba-1f12-4a81-92a0-015d59a12b57" />
