### ISSUE TITLE
Hardware requirements

### ISSUE THREAD

**Issue by goldfishl** [linyiLYi/street-fighter-ai#8]
林哥，

Will the 3070's 8GB of RAM meet the minimum training requirements?

 I would like to know some hardware requirements when running parallel training in your video.

**Comment by linyiLYi** [comment]
我训练用的是 3080Ti，你可以跑一下 train.py 试一下，如果没报错就是 OK 的，Nature CNN 网络不是很吃显存

**Comment by goldfishl** [comment]
Thank you very much for your reply! And I hope you continue to be productive while maintaining a high level of quality!
