### ISSUE TITLE
Does anyone have a issue about PDF files that cannot be displayed?

### ISSUE THREAD

**Issue by laosuan** [linyiLYi/street-fighter-ai#9]
most of PDF files in chats directory cannot be displayed in my computer(ubuntu20.14)

**Comment by linyiLYi** [comment]
Perhaps the files are too large. I generated and viewed these pdf files on macOS using its default pdf reader.

**Comment by laosuan** [comment]
> Perhaps the files are too large. I generated and viewed these pdf files on macOS using its default pdf reader.

It can be displayed in Edge broswer. Thank you.
